var CoursesTags = [
  { courseId: 'course1', tagId: 'tag1' },
  { courseId: 'course2', tagId: 'tag2' },
  { courseId: 'course3', tagId: 'tag3' },
  { courseId: 'course4', tagId: 'tag4' },
  { courseId: 'course5', tagId: 'tag5' },
  { courseId: 'course6', tagId: 'tag6' },
  { courseId: 'course7', tagId: 'tag7' },
  { courseId: 'course8', tagId: 'tag8' },
  { courseId: 'course9', tagId: 'tag9' },
  { courseId: 'course10', tagId: 'tag10' },
  { courseId: 'course11', tagId: 'tag11' },
  { courseId: 'course12', tagId: 'tag12' },
  { courseId: 'course13', tagId: 'tag13' },
  { courseId: 'course14', tagId: 'tag14' },
  { courseId: 'course15', tagId: 'tag15' },
  { courseId: 'course16', tagId: 'tag16' },
  { courseId: 'course17', tagId: 'tag17' },
  { courseId: 'course18', tagId: 'tag18' },
  { courseId: 'course19', tagId: 'tag19' },
  { courseId: 'course20', tagId: 'tag20' },
];
