var Modules = [
  {
    id: 'module1',
    courseId: 'course1',
    title: 'Getting Started',
    content: 'Basics of Python programming.',
  },
  {
    id: 'module2',
    courseId: 'course1',
    title: 'Control Structures',
    content: 'Learn about loops and conditionals.',
  },
  {
    id: 'module3',
    courseId: 'course2',
    title: 'ES6 Features',
    content: 'Explore new features in ES6.',
  },
  {
    id: 'module4',
    courseId: 'course2',
    title: 'Async Programming',
    content: 'Understanding Promises and Async/Await.',
  },
  {
    id: 'module5',
    courseId: 'course3',
    title: 'Introduction to R',
    content: 'Basics of the R programming language.',
  },
  {
    id: 'module6',
    courseId: 'course3',
    title: 'Data Visualization',
    content: 'Learn how to visualize data with ggplot2.',
  },
  {
    id: 'module7',
    courseId: 'course4',
    title: 'HTML & CSS',
    content: 'Basics of web design with HTML and CSS.',
  },
  {
    id: 'module8',
    courseId: 'course4',
    title: 'Backend Development',
    content: 'Introduction to server-side programming with Node.js.',
  },
  {
    id: 'module9',
    courseId: 'course5',
    title: 'Supervised Learning',
    content: 'Understanding supervised learning algorithms.',
  },
  {
    id: 'module10',
    courseId: 'course5',
    title: 'Unsupervised Learning',
    content: 'Explore clustering and dimensionality reduction techniques.',
  },
  {
    id: 'module11',
    courseId: 'course6',
    title: 'Network Security',
    content: 'Basics of securing networks.',
  },
  {
    id: 'module12',
    courseId: 'course6',
    title: 'Cryptography',
    content: 'Introduction to encryption and decryption.',
  },
  {
    id: 'module13',
    courseId: 'course7',
    title: 'Cloud Models',
    content: 'Understanding SaaS, PaaS, and IaaS.',
  },
  {
    id: 'module14',
    courseId: 'course7',
    title: 'Cloud Providers',
    content: 'Overview of major cloud service providers.',
  },
  {
    id: 'module15',
    courseId: 'course8',
    title: 'HTML5 & CSS3',
    content: 'Advanced HTML5 and CSS3 techniques.',
  },
  {
    id: 'module16',
    courseId: 'course8',
    title: 'JavaScript Frameworks',
    content: 'Introduction to React and Vue.js.',
  },
  {
    id: 'module17',
    courseId: 'course9',
    title: 'SQL Basics',
    content: 'Introduction to SQL and database queries.',
  },
  {
    id: 'module18',
    courseId: 'course9',
    title: 'Database Design',
    content: 'Designing relational databases and schema design.',
  },
  {
    id: 'module19',
    courseId: 'course10',
    title: 'CI/CD Pipelines',
    content:
      'Introduction to Continuous Integration and Continuous Deployment.',
  },
  {
    id: 'module20',
    courseId: 'course10',
    title: 'Infrastructure as Code',
    content:
      'Understanding infrastructure automation with tools like Terraform.',
  },
  {
    id: 'module21',
    courseId: 'course11',
    title: 'SEO Basics',
    content: 'Fundamentals of Search Engine Optimization.',
  },
  {
    id: 'module22',
    courseId: 'course11',
    title: 'Social Media Marketing',
    content: 'Effective strategies for social media marketing.',
  },
  {
    id: 'module23',
    courseId: 'course12',
    title: 'AI Fundamentals',
    content: 'Understanding the basics of artificial intelligence.',
  },
  {
    id: 'module24',
    courseId: 'course12',
    title: 'Machine Learning Models',
    content: 'Introduction to common machine learning models.',
  },
  {
    id: 'module25',
    courseId: 'course13',
    title: 'Complex Joins',
    content: 'Understanding complex joins and subqueries.',
  },
  {
    id: 'module26',
    courseId: 'course13',
    title: 'Performance Tuning',
    content: 'Optimizing SQL queries for better performance.',
  },
  {
    id: 'module27',
    courseId: 'course14',
    title: 'UX Fundamentals',
    content: 'Basics of user experience design.',
  },
  {
    id: 'module28',
    courseId: 'course14',
    title: 'Design Thinking',
    content: 'Understanding the design thinking process.',
  },
  {
    id: 'module29',
    courseId: 'course15',
    title: 'Agile Principles',
    content: 'Overview of Agile principles and methodologies.',
  },
  {
    id: 'module30',
    courseId: 'course15',
    title: 'Scrum Framework',
    content: 'Introduction to Scrum roles, events, and artifacts.',
  },
  {
    id: 'module31',
    courseId: 'course16',
    title: 'Blockchain Fundamentals',
    content: 'Understanding blockchain technology and its components.',
  },
  {
    id: 'module32',
    courseId: 'course16',
    title: 'Cryptocurrency',
    content: 'Introduction to cryptocurrencies and their workings.',
  },
  {
    id: 'module33',
    courseId: 'course17',
    title: 'Camera Settings',
    content: 'Understanding camera settings and exposure.',
  },
  {
    id: 'module34',
    courseId: 'course17',
    title: 'Photo Editing',
    content: 'Basic photo editing techniques using software.',
  },
  {
    id: 'module35',
    courseId: 'course18',
    title: 'Writing Techniques',
    content: 'Exploring different writing techniques and styles.',
  },
  {
    id: 'module36',
    courseId: 'course18',
    title: 'Storytelling',
    content: 'Understanding the elements of storytelling.',
  },
  {
    id: 'module37',
    courseId: 'course19',
    title: 'Accounting Basics',
    content: 'Overview of accounting principles and practices.',
  },
  {
    id: 'module38',
    courseId: 'course19',
    title: 'Financial Statements',
    content: 'Understanding balance sheets and income statements.',
  },
  {
    id: 'module39',
    courseId: 'course20',
    title: 'Sociological Theories',
    content: 'Overview of major sociological theories.',
  },
  {
    id: 'module40',
    courseId: 'course20',
    title: 'Social Institutions',
    content: 'Understanding social institutions and their roles.',
  },
];
