var tags = [
  { id: 'tag1', name: 'Programming' },
  { id: 'tag2', name: 'JavaScript' },
  { id: 'tag3', name: 'Data Science' },
  { id: 'tag4', name: 'Web Development' },
  { id: 'tag5', name: 'Machine Learning' },
  { id: 'tag6', name: 'Cybersecurity' },
  { id: 'tag7', name: 'Cloud Computing' },
  { id: 'tag8', name: 'Front-end Development' },
  { id: 'tag9', name: 'Database' },
  { id: 'tag10', name: 'DevOps' },
  { id: 'tag11', name: 'Marketing' },
  { id: 'tag12', name: 'AI' },
  { id: 'tag13', name: 'SQL' },
  { id: 'tag14', name: 'UX Design' },
  { id: 'tag15', name: 'Agile' },
  { id: 'tag16', name: 'Blockchain' },
  { id: 'tag17', name: 'Photography' },
  { id: 'tag18', name: 'Creative Writing' },
  { id: 'tag19', name: 'Accounting' },
  { id: 'tag20', name: 'Sociology' },
];
