var Users = [
  {
    id: 'john_doe',
    username: 'john_doe',
    email: 'john.doe@example.com',
    password: 'hashed_password_1',
    role: 'student',
    profile: {
      firstName: 'John',
      lastName: 'Doe',
      bio: 'A passionate learner.',
    },
  },
  {
    id: 'jane_smith',
    username: 'jane_smith',
    email: 'jane.smith@example.com',
    password: 'hashed_password_2',
    role: 'instructor',
    profile: {
      firstName: 'Jane',
      lastName: 'Smith',
      bio: 'Experienced instructor in data science.',
    },
  },
  {
    id: 'alice_jones',
    username: 'alice_jones',
    email: 'alice.jones@example.com',
    password: 'hashed_password_3',
    role: 'student',
    profile: {
      firstName: 'Alice',
      lastName: 'Jones',
      bio: 'Eager to learn new skills.',
    },
  },
  {
    id: 'bob_brown',
    username: 'bob_brown',
    email: 'bob.brown@example.com',
    password: 'hashed_password_4',
    role: 'instructor',
    profile: {
      firstName: 'Bob',
      lastName: 'Brown',
      bio: 'Specialist in web development.',
    },
  },
  {
    id: 'carol_white',
    username: 'carol_white',
    email: 'carol.white@example.com',
    password: 'hashed_password_5',
    role: 'student',
    profile: {
      firstName: 'Carol',
      lastName: 'White',
      bio: 'Avid reader and learner.',
    },
  },
  {
    id: 'david_black',
    username: 'david_black',
    email: 'david.black@example.com',
    password: 'hashed_password_6',
    role: 'instructor',
    profile: {
      firstName: 'David',
      lastName: 'Black',
      bio: 'Experienced developer and teacher.',
    },
  },
  {
    id: 'eve_green',
    username: 'eve_green',
    email: 'eve.green@example.com',
    password: 'hashed_password_7',
    role: 'student',
    profile: {
      firstName: 'Eve',
      lastName: 'Green',
      bio: 'Motivated and curious learner.',
    },
  },
  {
    id: 'frank_blue',
    username: 'frank_blue',
    email: 'frank.blue@example.com',
    password: 'hashed_password_8',
    role: 'instructor',
    profile: {
      firstName: 'Frank',
      lastName: 'Blue',
      bio: 'Expert in data science and analytics.',
    },
  },
  {
    id: 'grace_pink',
    username: 'grace_pink',
    email: 'grace.pink@example.com',
    password: 'hashed_password_9',
    role: 'student',
    profile: {
      firstName: 'Grace',
      lastName: 'Pink',
      bio: 'Aspiring software developer.',
    },
  },
  {
    id: 'hank_orange',
    username: 'hank_orange',
    email: 'hank.orange@example.com',
    password: 'hashed_password_10',
    role: 'instructor',
    profile: {
      firstName: 'Hank',
      lastName: 'Orange',
      bio: 'Specializes in cybersecurity.',
    },
  },
  {
    id: 'irene_red',
    username: 'irene_red',
    email: 'irene.red@example.com',
    password: 'hashed_password_11',
    role: 'student',
    profile: {
      firstName: 'Irene',
      lastName: 'Red',
      bio: 'Passionate about machine learning.',
    },
  },
  {
    id: 'jack_yellow',
    username: 'jack_yellow',
    email: 'jack.yellow@example.com',
    password: 'hashed_password_12',
    role: 'instructor',
    profile: {
      firstName: 'Jack',
      lastName: 'Yellow',
      bio: 'Seasoned web developer and trainer.',
    },
  },
  {
    id: 'karen_cyan',
    username: 'karen_cyan',
    email: 'karen.cyan@example.com',
    password: 'hashed_password_13',
    role: 'student',
    profile: {
      firstName: 'Karen',
      lastName: 'Cyan',
      bio: 'Interested in artificial intelligence.',
    },
  },
  {
    id: 'leo_magenta',
    username: 'leo_magenta',
    email: 'leo.magenta@example.com',
    password: 'hashed_password_14',
    role: 'instructor',
    profile: {
      firstName: 'Leo',
      lastName: 'Magenta',
      bio: 'Expert in cloud computing.',
    },
  },
  {
    id: 'mona_lime',
    username: 'mona_lime',
    email: 'mona.lime@example.com',
    password: 'hashed_password_15',
    role: 'student',
    profile: {
      firstName: 'Mona',
      lastName: 'Lime',
      bio: 'Enthusiastic about software engineering.',
    },
  },
  {
    id: 'nina_violet',
    username: 'nina_violet',
    email: 'nina.violet@example.com',
    password: 'hashed_password_16',
    role: 'instructor',
    profile: {
      firstName: 'Nina',
      lastName: 'Violet',
      bio: 'Specializes in front-end development.',
    },
  },
  {
    id: 'oliver_brown',
    username: 'oliver_brown',
    email: 'oliver.brown@example.com',
    password: 'hashed_password_17',
    role: 'student',
    profile: {
      firstName: 'Oliver',
      lastName: 'Brown',
      bio: 'Curious about full-stack development.',
    },
  },
  {
    id: 'paula_gray',
    username: 'paula_gray',
    email: 'paula.gray@example.com',
    password: 'hashed_password_18',
    role: 'instructor',
    profile: {
      firstName: 'Paula',
      lastName: 'Gray',
      bio: 'Experienced in project management.',
    },
  },
  {
    id: 'quinn_silver',
    username: 'quinn_silver',
    email: 'quinn.silver@example.com',
    password: 'hashed_password_19',
    role: 'student',
    profile: {
      firstName: 'Quinn',
      lastName: 'Silver',
      bio: 'Avid learner of new technologies.',
    },
  },
  {
    id: 'rachel_gold',
    username: 'rachel_gold',
    email: 'rachel.gold@example.com',
    password: 'hashed_password_20',
    role: 'instructor',
    profile: {
      firstName: 'Rachel',
      lastName: 'Gold',
      bio: 'Expert in database management.',
    },
  },
];
